# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

commands:
  update_apt:
    description: update apt packages
    steps:
      - run: apt update
  install_tar_gzip:
    description: install tar and gzip in amazon/aws-cli docker image
    steps:
      - run:
          name: Install tar utility
          command: yum install -y tar gzip
  delete_stack:
    description: delete created stack on failure
    steps:
      - run:
          name: Install AWSCli on alpine instances
          command: apt install -y awscli
          when: on_fail
      - run:
          name: Delete stack only if command before failed
          command: aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID}
          when: on_fail

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - install_tar_gzip
      - run:
          name: Create Cloudformation Stack
          command: >
            aws cloudformation deploy
            --template-file template.yml
            --stack-name myStack-${CIRCLE_WORKFLOW_ID}
            --region us-east-1
      - run:
          name: Create inventory file
          command: echo "[all]" > inventory
      - run:
          name: Insert EC2 IP into inventory
          command: >
            aws ec2 describe-instances
            --query 'Reservations[*].Instances[*].PublicIpAddress'
            --filters "Name=tag-key,Values=aws:cloudformation:stack-name"
            "Name=tag-value,Values=myStack-${CIRCLE_WORKFLOW_ID}"
            --output text >> inventory
      - run:
          name: check if there is IP in inventory
          command: "[ $(cat inventory | wc -l) != '1' ]"
      - delete_stack
      - persist_to_workspace:
          root: .
          paths:
            - inventory

  configure_infrastructure:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints: [$AWS_SSH_FINGERPRINT]
      - update_apt
      - run:
          name: Install Ansible
          command: pip install ansible -y
      - run:
          name: Run Playbook and Configure server
          command: ansible-playbook -i inventory my-main.yml
      - delete_stack

  smoke_test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - update_apt
      - run:
          name: Install curl
          command: apt install -y curl
      - run:
          name: smoke test
          command: |
            return 1
      - delete_stack


workflows:
  my_workflow:
    jobs:
      - create_infrastructure
      - configure_infrastructure:
          requires: [create_infrastructure]
      - smoke_test:
          requires: [configure_infrastructure]
