---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install npm and nodejs"
  become: yes
  apt:
    name: [npm, nodejs]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create web dir"
  file:
    path: ~/web
    state: directory

- name: "copy index.js to web dir"
  copy:
    src: index.js
    dest: ~/web/index.js

- name: "start web server"
  shell: pm2 start ~/web/index.js -f